name: bookque
description: capstone project cpsg10

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  google_sign_in: ^5.3.2
  firebase_messaging: ^11.4.2
  flutter_facebook_auth: ^4.3.4
  flutter_local_notifications: ^9.6.1
  http: ^0.13.4
  provider: ^6.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  sqflite: ^2.0.2+1
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  smooth_page_indicator: ^1.0.0+2
  sliding_sheet: ^0.5.2
  equatable: ^2.0.2
  salomon_bottom_bar: ^3.3.1
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.2
  group_button: ^5.0.1
  cached_network_image: ^3.2.1
  image: ^3.1.3
  extended_image: ^6.2.1
  lazy_load_indexed_stack: ^0.1.3
  flutter_staggered_animations: ^1.0.0
  shared_preferences: ^2.0.15
  firebase_crashlytics: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
