// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4TyOEoxXZlKguJxcq2l24C8B04CFByP0',
    appId: '1:135434374178:android:b2ba806ac98faa96c04e7b',
    messagingSenderId: '135434374178',
    projectId: 'bookque-cpsg10',
    storageBucket: 'bookque-cpsg10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTI8udPbTOVfucQ_2duUmJcleafIE5L04',
    appId: '1:135434374178:ios:7f06997997e3450ec04e7b',
    messagingSenderId: '135434374178',
    projectId: 'bookque-cpsg10',
    storageBucket: 'bookque-cpsg10.appspot.com',
    androidClientId: '135434374178-v35for70qlb0248b3is71urls40vjm01.apps.googleusercontent.com',
    iosClientId: '135434374178-slg44re4j59udvrg9u9f8e5bbjifidr3.apps.googleusercontent.com',
    iosBundleId: 'com.cpsg10.bookque',
  );
}
